/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frmcassino;

import java.text.ParseException;
import java.util.Random;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Jonatas Silvestrini
 */
public class frmCassino extends javax.swing.JFrame {

	/**
	 * Creates new form frmCassino
	 */
	//Declaração de variáveis globais e objetos
	float total = 1000.00f, aposta, n1, n2, n3, nSorteado;
	int tN1, tN2, tN3;
	Timer tNumero;
	Random gerador = new Random();

	public frmCassino() {
		initComponents();
		/*Cria uma máscara para não permitir a inserção de
		 *qualquer caractere que não seja um número.
		 */
		lblMsg.setText("<html><b>Faça sua aposta!</b></html>");
		lblTotal.setText(Float.toString(total));
		MaskFormatter maskPhone = null;
		try {
			maskPhone = new MaskFormatter("#############");
		} catch (ParseException ex) {
			Logger.getLogger(frmCassino.class.getName()).log(Level.SEVERE, null, ex);
		}
		maskPhone.install(txtfAposta);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jLabel4 = new javax.swing.JLabel();
                jLabel5 = new javax.swing.JLabel();
                lblTotal = new javax.swing.JLabel();
                lblAposta = new javax.swing.JLabel();
                btnGirar = new javax.swing.JButton();
                btnApostar = new javax.swing.JButton();
                txtfAposta = new javax.swing.JFormattedTextField();
                lblMsg = new javax.swing.JLabel();
                jPanel1 = new javax.swing.JPanel();
                lblN1 = new javax.swing.JLabel();
                lblN2 = new javax.swing.JLabel();
                lblN3 = new javax.swing.JLabel();
                jLabel1 = new javax.swing.JLabel();
                jLabel2 = new javax.swing.JLabel();

                setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
                setTitle("jCassino");
                setResizable(false);

                jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel4.setText("Total:");

                jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
                jLabel5.setText("Aposta:");

                lblTotal.setText("1");

                lblAposta.setText("0.0");

                btnGirar.setText("Girar");
                btnGirar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnGirarActionPerformed(evt);
                        }
                });

                btnApostar.setText("Apostar");
                btnApostar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnApostarActionPerformed(evt);
                        }
                });

                lblMsg.setText("Faça sua aposta!");

                jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

                lblN1.setFont(new java.awt.Font("Lucida Sans", 1, 96)); // NOI18N
                lblN1.setForeground(new java.awt.Color(255, 51, 51));
                lblN1.setText("7");

                lblN2.setFont(new java.awt.Font("Lucida Sans", 1, 96)); // NOI18N
                lblN2.setForeground(new java.awt.Color(255, 51, 51));
                lblN2.setText("7");

                lblN3.setFont(new java.awt.Font("Lucida Sans", 1, 96)); // NOI18N
                lblN3.setForeground(new java.awt.Color(255, 51, 51));
                lblN3.setText("7");

                javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
                jPanel1.setLayout(jPanel1Layout);
                jPanel1Layout.setHorizontalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(lblN1)
                                .addGap(18, 18, 18)
                                .addComponent(lblN2)
                                .addGap(18, 18, 18)
                                .addComponent(lblN3, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(28, Short.MAX_VALUE))
                );
                jPanel1Layout.setVerticalGroup(
                        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblN1)
                                        .addComponent(lblN3)
                                        .addComponent(lblN2))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                );

                jLabel1.setText("R$");

                jLabel2.setText("R$");

                javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
                getContentPane().setLayout(layout);
                layout.setHorizontalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel5)
                                                        .addComponent(jLabel4))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblTotal))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(lblAposta)))
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 1, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(lblMsg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(txtfAposta, javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(btnApostar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
                                                                .addGap(194, 194, 194)
                                                                .addComponent(btnGirar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addContainerGap())))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55))
                );
                layout.setVerticalGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel4)
                                        .addComponent(lblTotal)
                                        .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5)
                                        .addComponent(lblAposta)
                                        .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(3, 3, 3)
                                .addComponent(lblMsg, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(txtfAposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnApostar))
                                        .addComponent(btnGirar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                );

                pack();
                setLocationRelativeTo(null);
        }// </editor-fold>//GEN-END:initComponents

        private void btnApostarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApostarActionPerformed
		// TODO add your handling code here:
		if (!txtfAposta.getText().equals("           ")) { //Verica se o campo não foi deixado em branco
			aposta = Float.parseFloat(txtfAposta.getText()); //variavel aposta recebe o valor apostado
			if (aposta > total || aposta == 0) { //se for um valor maior que o total ou igual a zero exibe menssagem de rro
				JOptionPane.showMessageDialog(null, "Você não pode apostar esse valor!!!");//Exibe menssagem
			} else {
				total -= aposta; //Subtrai valor da aposta do total
				lblTotal.setText(Float.toString(total)); //Mostra valor total
				lblAposta.setText(Float.toString(aposta));//Mostra valor da aposta
				//Desabilita opção de aposta até próxima rodada
				txtfAposta.setEnabled(false);
				btnApostar.setEnabled(false);
			}
		} else {
			JOptionPane.showMessageDialog(rootPane, "Campo de aposta em branco!!");//Mostra menssagem se o campo estiver em branco
		}
        }//GEN-LAST:event_btnApostarActionPerformed

        private void btnGirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGirarActionPerformed
		// TODO add your handling code here:
		if (!btnApostar.isEnabled()) {     // verifica se a aposta foi feita
			btnGirar.setEnabled(false);// desabilita opção de jogar até a próxima rodada
			tNumero = new Timer(); //Instancia objeto novo Timer chamado tNumero
			//Gera números de vezes que irão rodar cada um dos 3 números da máquina
			tN1 = gerador.nextInt(40) + 80;
			tN2 = gerador.nextInt(40) + 80;
			tN3 = gerador.nextInt(40) + 80;
			//Essa parte é para Debug
			//System.out.println(tN1);
			//System.out.println(tN2);
			//System.out.println(tN3);
			tNumero.schedule(new GeradorAleatorio(), 0, 50);//Cria a Thread para sortear os números 
		} else {
			JOptionPane.showMessageDialog(rootPane, "Você precisa apostar um valor primeiro!!"); //Messagem de erro se não tem valor de aposta.
		}

        }//GEN-LAST:event_btnGirarActionPerformed
	class GeradorAleatorio extends TimerTask {

		int numero;

		public void run() {
			if (tN1 > 0 || tN2 > 0 || tN3 > 0) {
				if (tN1 > 0) {
					numero = gerador.nextInt(7) + 1;
					lblN1.setText(Integer.toString(numero));
					tN1--;
					//System.out.print("\u001B[39m" + tN1 + "|");
				}
				if (tN2 > 0) {
					numero = gerador.nextInt(7) + 1;
					lblN2.setText(Integer.toString(numero));
					tN2--;
					//System.out.print("\u001B[32m" + tN2 + "|");
				}
				if (tN3 > 0) {
					numero = gerador.nextInt(7) + 1;
					lblN3.setText(Integer.toString(numero));
					tN3--;
					//System.out.print("\u001B[31m" + tN3 + "|");
				}

			} else {
				n1 = Float.parseFloat(lblN1.getText());
				n2 = Float.parseFloat(lblN2.getText());
				n3 = Float.parseFloat(lblN3.getText());
				if (n1 == n2 || n1 == n3 || n2 == n3 || (n1 == n2 && n2 == n3)) {
					if (n1 == n2 || n1 == n3) {
						if (n2 == n3) {
							nSorteado = n1 * 2f;
						} else {
							if (n1 == 1) {
								nSorteado = n1;
							} else {
								nSorteado = n1 / 1.5f;
							}
						}
					} else {
						if (n2 == 1) {
							nSorteado = n2;
						} else {
							nSorteado = n2 / 1.5f;
						}
					}
					aposta *= nSorteado;
					lblMsg.setText("<html><p style=\"color:green;font-size:12px;\"><b>Parabéns, você ganhou R$ " + aposta + "</b></p></html>");
					total += aposta;
				} else {
					lblMsg.setText("<html><p style=\"color:red;font-size:12px;\"><b>Que pena! Você perdeu. Tente novamente!</b></p></html>");
				}
				//System.out.println("");
				aposta = 0;
				lblTotal.setText(Float.toString(total));
				lblAposta.setText(Float.toString(aposta));
				if (total == 0) {
					int fim = JOptionPane.showConfirmDialog(rootPane, "Fim de jogo! Deseja jogar novamente?", "Fim", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
					if (fim == 0) {
						total = 1000;
						lblTotal.setText(Float.toString(total));
						lblMsg.setText("<html><b>Faça sua aposta!</b></html>");
						lblN1.setText("7");
						lblN2.setText("7");
						lblN3.setText("7");
						txtfAposta.setText("");
					} else {
						System.exit(0);
					}
				}
				//System.out.println("Fim Thread");
				btnApostar.setEnabled(true);
				txtfAposta.setEnabled(true);
				btnGirar.setEnabled(true);
				tNumero.cancel();
			}
		}
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmCassino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmCassino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmCassino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmCassino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmCassino().setVisible(true);
			}
		});
	}

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnApostar;
        private javax.swing.JButton btnGirar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel4;
        private javax.swing.JLabel jLabel5;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JLabel lblAposta;
        private javax.swing.JLabel lblMsg;
        private javax.swing.JLabel lblN1;
        private javax.swing.JLabel lblN2;
        private javax.swing.JLabel lblN3;
        private javax.swing.JLabel lblTotal;
        private javax.swing.JFormattedTextField txtfAposta;
        // End of variables declaration//GEN-END:variables
}
